[toolchain]
package_manager = "yarn"

[workspace]
members = ["programs/*", "packages/*"]

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_anchor_project = "AgBHPG2xUS1iWmbvwdrjWxcNTqudqtwGoYGe1iPF7gDF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy = "anchor deploy"